### ISSUE TITLE
Odin issue

### ISSUE THREAD

**Issue by Redruby110** [rainbowdashh/android_device_samsung_b4q#1]
TNX for this Project. 🙏👌
I couldn't install via Odin V14.3.0 .do you have any specific instructions, for install on Z flip 4 (SM-F721)?
tnx 🙏

**Comment by rainbowdashh** [comment]
Just rename the image file into recovery.img and add it to an otherwise empty .tar archive. That's how odin works.
I re-uploaded one now for you in the releases tab, so it should work.

**Comment by Redruby110** [comment]
Thank you so much for your help.
